# fly.toml app configuration file generated for weblangchain on 2023-10-03T20:09:50-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weblangchain"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]
